# Generated by Django 5.2.4 on 2025-07-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(related_name='batches', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='taught_by',
            field=models.ManyToManyField(to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.department'),
        ),
    ]
